version: '3.8'
services:
  lp-server:
    build:
      context: .
    image: lp-server:latest
    container_name: lp-server
    ports:
      - "8080:8080"
    restart: always
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: lp_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_lp:/var/lib/mysql

volumes:
  mysql_data_lp: